"""empty message

Revision ID: ec6a4d70d1ec
Revises: 5a1688e27af9
Create Date: 2025-02-14 14:20:33.634321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6a4d70d1ec'
down_revision = '5a1688e27af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=False),
    sa.Column('disco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurso')
    # ### end Alembic commands ###
